/**
 * The bundled overlay PNGs, as Metro require() calls.
 *
 * GENERATED by Detailcharts/scripts/dump_app_fixture.py — do not edit by hand.
 *
 * Metro resolves `require` at build time and cannot take a computed path, so every
 * frame has to be written out. That is the whole reason this file exists separately
 * from the manifests it belongs to.
 */

export const FIELD_FIXTURE_PNGS: Record<string, number> = {
  'humidity/20260626T2100Z': require('../../assets/fields/humidity/20260626T2100Z.png'),
  'humidity/20260626T2110Z': require('../../assets/fields/humidity/20260626T2110Z.png'),
  'humidity/20260626T2120Z': require('../../assets/fields/humidity/20260626T2120Z.png'),
  'humidity/20260626T2130Z': require('../../assets/fields/humidity/20260626T2130Z.png'),
  'humidity/20260626T2140Z': require('../../assets/fields/humidity/20260626T2140Z.png'),
  'humidity/20260626T2150Z': require('../../assets/fields/humidity/20260626T2150Z.png'),
  'humidity/20260626T2200Z': require('../../assets/fields/humidity/20260626T2200Z.png'),
  'humidity/20260626T2210Z': require('../../assets/fields/humidity/20260626T2210Z.png'),
  'humidity/20260626T2220Z': require('../../assets/fields/humidity/20260626T2220Z.png'),
  'humidity/20260626T2230Z': require('../../assets/fields/humidity/20260626T2230Z.png'),
  'humidity/20260626T2240Z': require('../../assets/fields/humidity/20260626T2240Z.png'),
  'humidity/20260626T2250Z': require('../../assets/fields/humidity/20260626T2250Z.png'),
  'temperature/20260626T2100Z': require('../../assets/fields/temperature/20260626T2100Z.png'),
  'temperature/20260626T2110Z': require('../../assets/fields/temperature/20260626T2110Z.png'),
  'temperature/20260626T2120Z': require('../../assets/fields/temperature/20260626T2120Z.png'),
  'temperature/20260626T2130Z': require('../../assets/fields/temperature/20260626T2130Z.png'),
  'temperature/20260626T2140Z': require('../../assets/fields/temperature/20260626T2140Z.png'),
  'temperature/20260626T2150Z': require('../../assets/fields/temperature/20260626T2150Z.png'),
  'temperature/20260626T2200Z': require('../../assets/fields/temperature/20260626T2200Z.png'),
  'temperature/20260626T2210Z': require('../../assets/fields/temperature/20260626T2210Z.png'),
  'temperature/20260626T2220Z': require('../../assets/fields/temperature/20260626T2220Z.png'),
  'temperature/20260626T2230Z': require('../../assets/fields/temperature/20260626T2230Z.png'),
  'temperature/20260626T2240Z': require('../../assets/fields/temperature/20260626T2240Z.png'),
  'temperature/20260626T2250Z': require('../../assets/fields/temperature/20260626T2250Z.png'),
  'wind/20260626T2100Z': require('../../assets/fields/wind/20260626T2100Z.png'),
  'wind/20260626T2110Z': require('../../assets/fields/wind/20260626T2110Z.png'),
  'wind/20260626T2120Z': require('../../assets/fields/wind/20260626T2120Z.png'),
  'wind/20260626T2130Z': require('../../assets/fields/wind/20260626T2130Z.png'),
  'wind/20260626T2140Z': require('../../assets/fields/wind/20260626T2140Z.png'),
  'wind/20260626T2150Z': require('../../assets/fields/wind/20260626T2150Z.png'),
  'wind/20260626T2200Z': require('../../assets/fields/wind/20260626T2200Z.png'),
  'wind/20260626T2210Z': require('../../assets/fields/wind/20260626T2210Z.png'),
  'wind/20260626T2220Z': require('../../assets/fields/wind/20260626T2220Z.png'),
  'wind/20260626T2230Z': require('../../assets/fields/wind/20260626T2230Z.png'),
  'wind/20260626T2240Z': require('../../assets/fields/wind/20260626T2240Z.png'),
  'wind/20260626T2250Z': require('../../assets/fields/wind/20260626T2250Z.png'),
};
